apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv

spec:
  capacity:
    storage: 10Gi

  accessModes:
    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain

  storageClassName: nfs-storage

  volumeMode: Filesystem

  nfs:
    server: <NFS_SERVER_IP>
    path: /data
