apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-backend-database-connection
  namespace: ecommerce
type: Opaque

stringData:
  MARIADB_DB: "full-stack-ecommerce"
  MARIADB_HOST: "<MARIADB_HOST>"
  MARIADB_PORT: "3306"
  MARIADB_USERNAME: "<MARIADB_USERNAME>"
  MARIADB_PASSWORD: "<MARIADB_PASSWORD>"
  FRONTEND_URL: "https://<FRONTEND_DOMAIN>"
  OKTA_CLIENT_ID: "<OKTA_CLIENT_ID>"
  OKTA_ISSUER: "https://<OKTA_ISSUER>"
