apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: architecture
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: node
    app.kubernetes.io/instance: redis-sentinel
    app.kubernetes.io/name: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
    - name: sentinel
      port: 26379
      targetPort: sentinel
